// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStory struct {
	Text     string `json:"text"`
	Category string `json:"category"`
	UserID   string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
